#!/bin/bash

# Example usage: ./check submissions/accepted/add_arbitrary.py data/sample/sample_00_main

# A simple checker script that runs a program against an input. Nice to use for
# local testing. You may need to modify the exact run commands to work on your
# system.

# passed=1

for i in data/secret/*.in; do
  # strip the extension
  test_path="${i%.*}"
  # get testname (strip path)
  test_name=$(basename -- "$test_path")
  result=0
  echo "Running $test_path"
  if [[ "$1" == *.py ]] # Python 3
  then
    python3 "$1" < "$test_path.in" > "out/$test_name.out"
    if ! ./executables/compare/compare.py "$test_path.in" "$test_path.ans" < "out/$test_name.out"; then
      echo "failed on test $test_path"
      diff -Z "$test_path.ans" "out/$test_name.out"
    fi
  # elif [[ "$1" == *java ]] # Java
  # then
  #   javac "$1" -d ./bin
  #   output=$(java -cp ./bin "$1" < "$2.in" | diff -Z "$2.ans" -)
  #   rm -rf ./bin
  else
    echo "Unrecognized solution format: $1";
  fi
done
